### ISSUE TITLE
botocore.exceptions.NoRegionError: You must specify a region.

### ISSUE THREAD

**Issue by lilith-saer-wwt** [mickep76/docker-build-ami#10]
Hi there. I am trying to use this library but I keep seeing errors about specify a region from boto. This is my config:

```
[main]

# Temporary directory
tmp_dir = /tmp

# Name tag for host building AMI image
host_tag = 'docker-build-ami'

# Region
region = us-east-1

# Instance type
instance_type = m3.medium

# Subnet ID
subnet_id = xxxxx

# Security Groups
security_group_ids = ["xxxx"]

# Host Tags - additional tags to add to EC2 host
# host_tags = [{"Key": "foo", "Value": "bar"}]

# AWS access key id
aws_access_key_id = xxxxx

# AWS secret access key
aws_secret_access_key = xxxxx

# Base image from which the output image is built
# image_id = ami-0df67e2624dedbae1

# EC2 user used to build instances (usually AMI dependent)
# image_user = ubuntu

# The AMI Name of the output image
image_name = falcon-sensor-ami

# Image Tags - tags to add to AMI
# image_tags = [{"Key": "foo", "Value": "bar"}]

```

Here is the stacktrace:

```
docker-build-ami -c ./.docker-build-ami.conf -r us-east-1
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jamieleecho_docker_build_ami-0.7.0-py3.9.egg/docker2ami/ami_builder.py", line 92, in start
  File "/usr/local/lib/python3.9/site-packages/boto3-1.20.46-py3.9.egg/boto3/__init__.py", line 102, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/boto3-1.20.46-py3.9.egg/boto3/session.py", line 396, in resource
    client = self.client(
  File "/usr/local/lib/python3.9/site-packages/boto3-1.20.46-py3.9.egg/boto3/session.py", line 270, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/session.py", line 870, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/client.py", line 91, in create_client
    client_args = self._get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/client.py", line 360, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/args.py", line 148, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/args.py", line 234, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/args.py", line 320, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/client.py", line 441, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/regions.py", line 181, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/usr/local/lib/python3.9/site-packages/botocore-1.23.46-py3.9.egg/botocore/regions.py", line 215, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/docker-build-ami", line 33, in <module>
    sys.exit(load_entry_point('jamieleecho-docker-build-ami==0.7.0', 'console_scripts', 'docker-build-ami')())
  File "/usr/local/lib/python3.9/site-packages/jamieleecho_docker_build_ami-0.7.0-py3.9.egg/docker2ami/docker2ami.py", line 149, in main
  File "/usr/local/lib/python3.9/site-packages/jamieleecho_docker_build_ami-0.7.0-py3.9.egg/docker2ami/docker2ami.py", line 137, in main_with_args
  File "/usr/local/lib/python3.9/site-packages/jamieleecho_docker_build_ami-0.7.0-py3.9.egg/docker2ami/ami_builder.py", line 218, in __enter__
  File "/usr/local/lib/python3.9/site-packages/jamieleecho_docker_build_ami-0.7.0-py3.9.egg/docker2ami/ami_builder.py", line 94, in start
RuntimeError: Failed to connect to EC2
```

**Comment by lilith-saer-wwt** [comment]
Running `export AWS_DEFAULT_REGION=us-east-1` in the console helped to resolve this issue.
